import { expect, test } from '@playwright/test';
import { openSimulationContext } from './shell.js';

test('ward search, review filters and chart keyboard navigation work', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Work email').fill('review@example.test');
  await page.getByLabel('Password', { exact: true }).fill('fictional-review');
  await page.getByRole('button', { name: 'Enter simulation workspace' }).click();
  await expect(page.getByText('Current ward workflow:', { exact: false })).toBeVisible();
  const search = page.getByRole('searchbox', { name: 'Find a ward' });
  await search.fill('no matching fictional ward');
  await expect(page.getByText('No wards match. Try another name or specialty.')).toBeVisible();
  await search.clear();
  const card = page.locator('.ward-card').first();
  const name = await card.locator('strong').first().innerText();
  await card.focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('heading', { name, exact: true })).toBeFocused();
  await page.getByRole('combobox', { name: 'Care status', exact: true }).selectOption('review');
  await expect(page.locator('.hospital-patient-table tbody .rag-pill.rag-green')).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Care status', exact: true }).selectOption('all');
  const patient = page.locator('.patient-name-trigger').first();
  await patient.focus();
  await page.keyboard.press('Enter');
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole('button', { name: 'Close chart' })).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(dialog.getByRole('button', { name: 'Close chart' })).toBeFocused();
  const dimensions = await dialog.evaluate((node) => ({ client: node.clientWidth, scroll: node.scrollWidth }));
  expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.client + 1);
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0);
  await expect(patient).toBeFocused();
  await page.getByRole('button', { name: 'All wards', exact: false }).click();
  await expect(card).toBeFocused();
});

test('connected ward preserves patient observations, tasks and SBAR after reload', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Work email').fill('review@example.test');
  await page.getByLabel('Password', { exact: true }).fill('fictional-review');
  await page.getByRole('button', { name: 'Enter simulation workspace' }).click();
  await page.locator('.ward-card').first().click();
  const name = await page.locator('.patient-name-trigger').nth(1).innerText();
  await page.getByRole('button', { name: `Review ${name} in ward workspace` }).click();
  const patientId = await page.getByRole('combobox', { name: 'Selected patient', exact: true }).inputValue();
  await page.getByRole('button', { name: 'Record observations', exact: true }).click();
  await page.getByLabel('NEWS2', { exact: true }).fill('4');
  await page.getByRole('button', { name: 'Record simulated observation' }).click();
  await expect(page.getByText('Current NEWS2 4', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Review tasks', exact: true }).click();
  await page.getByRole('button', { name: 'Add task', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Patient', exact: true })).toHaveValue(patientId);
  await page.getByLabel('Task description').fill('Review fictional handover notes');
  await page.getByLabel('Owner', { exact: true }).fill('Simulation reviewer');
  await page.getByLabel('Due time').fill('12:30');
  await page.getByRole('button', { name: 'Save task' }).click();
  await page.getByRole('tab', { name: 'SBAR', exact: true }).click();
  await page.getByLabel('Editable SBAR draft').fill(`Fictional review for ${name}. Human review required.`);
  await page.getByRole('button', { name: 'Save SBAR draft', exact: true }).click();
  await page.reload();
  await expect(page.getByRole('combobox', { name: 'Selected patient', exact: true })).toHaveValue(patientId);
  await expect(page.getByText('Review fictional handover notes', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'SBAR', exact: true }).click();
  await expect(page.getByLabel('Editable SBAR draft')).toHaveValue(`Fictional review for ${name}. Human review required.`);
  await openSimulationContext(page);
  await page.getByRole('button', { name: 'Change ward', exact: true }).click();
  await expect(page.locator('.hospital-patient-table tbody tr').filter({ hasText: name })).toContainText('4');
  await page.getByRole('button', { name: 'All wards', exact: false }).click();
  await page.locator('.ward-card').nth(1).click();
  await page.getByRole('button', { name: 'Open this ward workspace' }).click();
  await expect(page.getByRole('combobox', { name: 'Selected patient', exact: true })).not.toHaveValue(patientId);
  await openSimulationContext(page);
  await page.getByRole('button', { name: 'Change ward', exact: true }).click();
  await page.getByRole('button', { name: 'All wards', exact: false }).click();
  await page.locator('.ward-card').first().click();
  await page.getByRole('button', { name: 'Open this ward workspace' }).click();
  await expect(page.getByRole('combobox', { name: 'Selected patient', exact: true })).toHaveValue(patientId);
  for (const width of [320, 390, 768, 1280, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
    expect(overflow, `Page overflow at ${width}px`).toBeLessThanOrEqual(1);
  }
});
